Repository yunahu/FlexyCook, pull requests merged in 2024-03, with the labels that each got.

#53 added a dropdown component #52
  src/components/DropdownMenu/DropdownMenu.jsx
  src/components/DropdownMenu/DropdownMenu.module.css
Labels: UI

#57 Advanced search
  src/components/DropdownMenu/DropdownMenu.jsx
  src/components/DropdownMenu/DropdownMenu.module.css
  src/components/Footer/Footer.module.css
  src/components/ModifiedButton/ModifiedButton.jsx
  src/components/ModifiedButton/ModifiedButton.module.css
  src/pages/Search/components/AdvancedSearch/AdvancedSearch.jsx
  src/pages/Search/components/AdvancedSearch/AdvancedSearch.module.css
  src/pages/Search/components/DeletableTag/DeletableTag.jsx
  src/pages/Search/components/DeletableTag/DeletableTag.module.css
  src/pages/Search/components/DividerWithText/DividerWithText.jsx
  src/pages/Search/components/DividerWithText/DividerWithText.module.css
  src/pages/Search/components/Search.jsx
  src/pages/Search/index.jsx
  src/pages/Search/utils/searchFunctions.js
  src/utils/common.js
Labels: Spoonacular, UI

#59 Horizontal cards
  package.json
  src/App.css
  src/components/Cards/CookingInfo/CookingInfo.jsx
  src/components/Cards/CookingInfo/CookingInfo.module.css
  src/components/Divider/Divider.jsx
  src/components/Divider/Divider.module.css
  src/pages/Home/Home.jsx
  src/pages/Home/Home.module.css
  src/pages/Home/components/CarouselBanner/CarouselBanner.module.css
  src/pages/Home/components/CarouselBanner/SingleCarousel/SingleCarousel.jsx
  src/pages/Home/components/CarouselBanner/SingleCarousel/SingleCarousel.module.css
  src/pages/Home/components/HorizontalCard/HorizontalCard.jsx
  src/pages/Home/components/HorizontalCard/HorizontalCard.module.css
  src/pages/Home/components/LargeSquareCard/LargeSquareCard.jsx
  src/pages/Home/components/LargeSquareCard/LargeSquareCard.module.css
Labels: UI

#64 Homepage with API call
  src/Router/Router.jsx
  src/components/Cards/Tags/Tags.jsx
  src/components/LargeSquareCard/LargeCard.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
  src/pages/Home/Home.jsx
  src/pages/Home/HomeTest.jsx
  src/pages/Home/components/CarouselBanner/CarouselBanner.jsx
  src/pages/Home/components/CarouselBanner/SingleCarousel/SingleCarousel.jsx
  src/pages/Home/components/FavoriteRecommendation/FavoriteRecommendation.jsx
  src/pages/Home/components/FavoriteRecommendation/utils/recommend.js
  src/pages/Home/components/RefreshButton/RefreshButton.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/Search.module.css
  src/pages/Search/components/AdvancedSearch/AdvancedSearch.jsx
  src/pages/Search/components/Search.jsx
  src/pages/Search/components/cards/card.jsx
  src/pages/Search/components/cards/card.module.css
  src/utils/spoonacularFunctions.js
Labels: Spoonacular

#65 created SearchPage component, which combine scroll & api call #25
  package-lock.json
  package.json
  src/Router/Router.jsx
  src/components/Cards/Tags/Tags.jsx
  src/pages/Home/HomeTest.jsx
  src/pages/Home/components/Card/index.jsx
  src/pages/Home/components/CarouselBanner/CarouselBanner.jsx
  src/pages/Search/components/SearchPage.jsx
Labels: Spoonacular

#63 Alignment fix of navbar and footer
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
  src/pages/Home/Home.module.css
Labels: UI

#66 fixed props and changes some component & file names
  src/pages/Search/Search.jsx
  src/pages/Search/components/Search.jsx
  src/pages/Search/components/SearchCard/SearchCard.jsx
  src/pages/Search/components/SearchCard/SearchCard.module.css
  src/pages/Search/components/SearchPage.jsx
  src/pages/Search/components/cards/card.jsx
Labels: bug, Spoonacular

#68 Added flexy-cook-api link to the README file
  README.md
Labels: documentation

#69 search by nutrients in search page is completed #26
  src/components/Navbar/NavDropdownMenu/NavDropdownMenu.jsx
  src/pages/Home/Home.jsx
  src/pages/Search/components/AdvancedSearch/AdvancedSearch.jsx
  src/pages/Search/components/AdvancedSearch/AdvancedSearch.module.css
  src/pages/Search/components/SearchPage.jsx
Labels: Spoonacular

#70 cooking step fetch is done #27
  src/Router/Router.jsx
  src/components/ModifiedButton/ModifiedButton.jsx
  src/components/ModifiedButton/ModifiedButton.module.css
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
  src/pages/Recipe/RecipeTest.jsx
  src/pages/Recipe/components/CookingStep/CookingStep.jsx
  src/pages/Search/components/AdvancedSearch/AdvancedSearch.jsx
  src/pages/Search/components/SearchCard/SearchCard.jsx
  src/pages/Search/components/SearchCard/SearchCard.module.css
  src/pages/Search/components/SearchPage.jsx
Labels: Spoonacular

#75 Search fix
  package-lock.json
  package.json
  src/components/LargeSquareCard/LargeCard.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Searchbar/SearchBar.module.css
  src/pages/Home/Home.jsx
  src/pages/Home/HomeTest.jsx
  src/pages/Home/components/LargeSquareCard/LargeSquareCard.jsx
  src/pages/Recipe/RecipeTest.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/components/SearchPage.jsx
  tests/setup.js
  vite.config.js
Labels: Spoonacular, test

#78 Unit test for check-in
  package-lock.json
  package.json
  tests/IntegrationTest/Spoonacular/SearchByNutrients/AdvancedSearch.test.jsx
  tests/UnitTest/Spoonacular/SearchByIngridients/SearchBar.test.jsx
  tests/UnitTest/Spoonacular/SearchByNutrients/DeletableTag.test.jsx
  tests/UnitTest/Spoonacular/SearchByNutrients/ModifiedButton.test.jsx
Labels: test

#85 Recipe banner & Sticky Toolbar
  src/App.css
  src/components/Cards/CookingInfo/CookingInfo.jsx
  src/components/Divider/Divider.module.css
  src/components/Navbar/Navbar.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.module.css
  src/pages/Home/Home.jsx
  src/pages/Recipe/Recipe.jsx
  src/pages/Recipe/Recipe.module.css
  src/pages/Recipe/components/CookingStep/CookingStep.module.css
  src/pages/Recipe/components/RecipeBanner/RecipeBanner.jsx
  src/pages/Recipe/components/RecipeBanner/RecipeBanner.module.css
  src/pages/Recipe/components/ToolBar/ToolBar.jsx
  src/pages/Recipe/components/ToolBar/ToolBar.module.css
  src/pages/Search/Search.jsx
  src/pages/Search/components/SearchPage.jsx
  tests/UnitTest/Spoonacular/SearchByIngridients/SearchBar.test.jsx
Labels: UI

#95 Integration check in
  package-lock.json
  package.json
  src/App.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomeTest.jsx
  src/pages/Home/components/FavoriteRecommendation/FavoriteRecommendation.jsx
  src/pages/Home/components/HorizontalCard/HorizontalCard.jsx
  src/pages/Home/components/LargeSquareCard/LargeSquareCard.jsx
  src/pages/Recipe/RecipeTest.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/components/AdvancedSearch/AdvancedSearch.jsx
  src/pages/Search/components/SearchPage.jsx
  src/services/spoonacular.js
  src/utils/spoonacularFunctions.js
  tests/IntegrationTest/Spoonacular/Recommendation/HomeTest.test.jsx
  tests/IntegrationTest/Spoonacular/Recommendation/RandomRecipeMock.json
  tests/IntegrationTest/Spoonacular/Recommendation/RecipeDetailMock.json
  tests/IntegrationTest/Spoonacular/Recommendation/RecipeTasteMock.json
  tests/IntegrationTest/Spoonacular/SearchByNutrients/AdvancedSearch.test.jsx
  tests/UnitTest/Spoonacular/SearchByNutrients/DeletableTag.test.jsx
  tests/UnitTest/Spoonacular/SearchByNutrients/ModifiedButton.test.jsx
Labels: Spoonacular, test

#106 Applied OnClick & Redirect Function to Horizontal Cards
  package.json
  src/pages/Home/Home.module.css
  src/pages/Home/HomeTest.jsx
  src/pages/Home/components/HorizontalCard/HorizontalCard.jsx
  src/pages/Home/components/HorizontalCard/HorizontalCard.module.css
  src/pages/Home/components/LargeSquareCard/LargeSquareCard.module.css
  src/pages/Recipe/RecipeTest.jsx
  src/pages/Recipe/components/ToolBar/ToolBar.jsx
  src/pages/Search/Search.module.css
  src/pages/Search/components/SearchCard/SearchCard.jsx
  src/pages/Search/components/SearchCard/SearchCard.module.css
  src/pages/Search/components/SearchPage.jsx
Labels: enhancement, UI

#107 Advanced search fix
  src/components/Navbar/Navbar.jsx
  src/components/SearchBar/SearchBar.jsx
  src/pages/Home/HomeTest.jsx
  src/pages/Home/components/CarouselBanner/CarouselBanner.jsx
  src/pages/Home/components/CarouselBanner/SingleCarousel/SingleCarousel.jsx
  src/pages/Home/components/HorizontalCard/HorizontalCard.jsx
  src/pages/Home/components/LargeSquareCard/LargeSquareCard.jsx
  src/pages/Recipe/RecipeTest.jsx
  src/pages/Recipe/components/RecipeBanner/RecipeBanner.jsx
  src/pages/Search/components/AdvancedSearch/AdvancedSearch.jsx
  src/pages/Search/components/SearchCard/SearchCard.jsx
  src/pages/Search/components/SearchPage.jsx
  src/services/spoonacular.js
  tests/IntegrationTest/Spoonacular/Recommendation/HomeTest.test.jsx
  tests/IntegrationTest/Spoonacular/SearchByIngridients/GetRecipeMock.json
  tests/IntegrationTest/Spoonacular/SearchByIngridients/GetRecipeTasteMock.json
  tests/IntegrationTest/Spoonacular/SearchByIngridients/SearchPage.test.jsx
  tests/IntegrationTest/Spoonacular/SearchByIngridients/SearchRecipeMock.json
  tests/IntegrationTest/Spoonacular/SearchByNutrients/AdvancedSearch.test.jsx
  tests/IntegrationTest/Todoist/Spoonacular/SearchByIngridients/SearchBar.test.jsx
  tests/IntegrationTest/Todoist/Spoonacular/SearchByNutrients/DeletableTag.test.jsx
  tests/IntegrationTest/Todoist/Spoonacular/SearchByNutrients/ModifiedButton.test.jsx
Labels: enhancement, Spoonacular, test

#109 RecipeTest fix
  src/pages/Home/HomeTest.jsx
  src/pages/Home/components/CarouselBanner/CarouselBanner.jsx
  src/pages/Home/components/CarouselBanner/SingleCarousel/SingleCarousel.jsx
  src/pages/Recipe/RecipeTest.jsx
  src/pages/Search/components/SearchPage.jsx
  src/utils/spoonacularFunctions.js
Labels: Spoonacular

#110 Search by tags
  src/components/Cards/Tags/Tags.jsx
  src/components/DropdownMenu/DropdownMenu.module.css
  src/components/Tag/Tag.jsx
  src/components/Tag/Tag.module.css
  src/pages/Home/HomeTest.jsx
  src/pages/Search/components/AdvancedSearch/AdvancedSearch.jsx
  src/pages/Search/components/SearchPage.jsx
  src/utils/spoonacularFunctions.js
Labels: Spoonacular

#111 Recommendation tags
  package-lock.json
  package.json
  src/components/Cards/Tags/Tags.jsx
  src/components/Cards/Tags/Tags.module.css
  src/components/Tag/Tag.module.css
  src/pages/Search/Search.module.css
  src/pages/Search/components/SearchCard/SearchCard.jsx
  src/pages/Search/components/SearchPage.jsx
  src/utils/recommendationTags.js
  src/utils/spoonacularFunctions.js
Labels: Spoonacular, UI

#114 Scale
  src/components/Cards/CookingInfo/CookingInfo.jsx
  src/components/Cards/Tags/Tags.jsx
  src/pages/Home/components/HorizontalCard/HorizontalCard.jsx
  src/pages/Recipe/Recipe.module.css
  src/pages/Recipe/RecipeTest.jsx
  src/pages/Recipe/components/RecipeBanner/RecipeBanner.jsx
  src/pages/Recipe/components/RecipeBanner/RecipeBanner.module.css
  src/pages/Recipe/components/ToolBar/ToolBar.jsx
  tests/UnitTest/Spoonacular/Recommendation/CookingInfo.test.jsx
  tests/UnitTest/Spoonacular/SearchByIngridients/SearchBar.test.jsx
  tests/UnitTest/Spoonacular/SearchByIngridients/Tags.test.jsx
  tests/UnitTest/Spoonacular/SearchByNutrients/DeletableTag.test.jsx
  tests/UnitTest/Spoonacular/SearchByNutrients/ModifiedButton.test.jsx
Labels: Spoonacular

#115 Unit test spoonacular
  tests/UnitTest/Spoonacular/Recommendation/LargeSquareCard.test.jsx
Labels: Spoonacular, test

#116 General UI fix
  src/components/Cards/CookingInfo/CookingInfo.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Navbar/NavDropdownMenu/NavDropdownMenu.jsx
  src/components/Navbar/NavDropdownMenu/NavDropdownMenu.module.css
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
  src/pages/Home/Home.jsx
  src/pages/Home/HomeTest.jsx
  src/pages/Home/components/CarouselBanner/CarouselBanner.jsx
  src/pages/Home/components/CarouselBanner/SingleCarousel/SingleCarousel.jsx
  src/pages/Home/components/HorizontalCard/HorizontalCard.jsx
  src/pages/Home/components/HorizontalCard/HorizontalCard.module.css
  src/pages/Search/Search.module.css
Labels: bug, UI

#119 Recipe fix
  src/services/spoonacular.js
  tests/IntegrationTest/Spoonacular/SearchByIngridients/SearchPage.test.jsx
Labels: bug, Spoonacular

#121 Todoist modal styling
  src/components/DropdownMenu/DropdownMenu.module.css
  src/components/Navbar/NavDropdownMenu/NavDropdownMenu.module.css
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
  src/components/TodoListsModal/TodoListsModal.jsx
  src/components/TodoListsModal/TodoListsModal.module.css
  src/components/TodoListsModal/components/TodoList/TodoList.jsx
  src/components/TodoListsModal/components/TodoList/TodoList.module.css
Labels: enhancement, todoist, UI
